// <auto-generated />
namespace Yostocks.Api.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class yostockmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yostockmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201806221244280_yostock-models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
